# Generated by Django 3.0.3 on 2020-02-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='end_producrion',
            new_name='end_production',
        ),
        migrations.AlterField(
            model_name='car',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='gearbox',
            field=models.SmallIntegerField(choices=[(0, 'отсутствует'), (1, 'механика'), (2, 'автомат'), (3, 'робот'), (4, 'вариатор'), (5, 'редуктор')], verbose_name='КПП'),
        ),
    ]
